import type { Product, Ingredient } from "./types"

export const baseIngredients: Ingredient[] = [
  { id: "meat", name: "Carne de Hambúrguer", price: 0, removable: false, addable: true, isDefault: true },
  { id: "cheese", name: "Queijo", price: 0, removable: true, addable: true, isDefault: true },
  { id: "lettuce", name: "Alface", price: 0, removable: true, addable: false, isDefault: true },
  { id: "tomato", name: "Tomate", price: 0, removable: true, addable: false, isDefault: true },
  { id: "onion", name: "Cebola", price: 0, removable: true, addable: false, isDefault: true },
  { id: "pickle", name: "Picles", price: 0, removable: true, addable: false, isDefault: true },
  { id: "sauce", name: "Molho Especial", price: 0, removable: true, addable: false, isDefault: true },
]

export const extraIngredients: Ingredient[] = [
  { id: "bacon", name: "Bacon", price: 5, removable: false, addable: true, isDefault: false },
  { id: "egg", name: "Ovo", price: 4, removable: false, addable: true, isDefault: false },
  { id: "extra-cheese", name: "Queijo Extra", price: 3, removable: false, addable: true, isDefault: false },
  { id: "extra-meat", name: "Carne Extra", price: 8, removable: false, addable: true, isDefault: false },
]

export const products: Product[] = [
  {
    id: "pole-position-burger",
    name: "Pole Position",
    description: "Hambúrguer clássico com queijo, alface, tomate e molho especial",
    basePrice: 28,
    category: "burger",
    image: "/gourmet-cheeseburger.png",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "pit-stop-burger",
    name: "Pit Stop",
    description: "Duplo de carne, queijo cheddar, bacon crocante e cebola caramelizada",
    basePrice: 38,
    category: "burger",
    image: "/double-burger-with-bacon.jpg",
    ingredients: [
      { id: "meat", name: "Carne de Hambúrguer", price: 0, removable: false, addable: true, isDefault: true },
      { id: "meat-2", name: "Carne de Hambúrguer (2ª)", price: 0, removable: false, addable: false, isDefault: true },
      { id: "cheese", name: "Queijo Cheddar", price: 0, removable: true, addable: true, isDefault: true },
      { id: "bacon", name: "Bacon", price: 0, removable: true, addable: true, isDefault: true },
      {
        id: "caramelized-onion",
        name: "Cebola Caramelizada",
        price: 0,
        removable: true,
        addable: false,
        isDefault: true,
      },
    ],
    includeFries: true,
  },
  {
    id: "grand-prix-burger",
    name: "Grand Prix",
    description: "O campeão! Triplo de carne, queijos, bacon, ovo e molhos especiais",
    basePrice: 48,
    category: "burger",
    image: "/triple-burger-gourmet-premium.jpg",
    ingredients: [
      { id: "meat", name: "Carne de Hambúrguer", price: 0, removable: false, addable: true, isDefault: true },
      { id: "meat-2", name: "Carne de Hambúrguer (2ª)", price: 0, removable: false, addable: false, isDefault: true },
      { id: "meat-3", name: "Carne de Hambúrguer (3ª)", price: 0, removable: false, addable: false, isDefault: true },
      { id: "cheese", name: "Queijo", price: 0, removable: true, addable: true, isDefault: true },
      { id: "bacon", name: "Bacon", price: 0, removable: true, addable: true, isDefault: true },
      { id: "egg", name: "Ovo", price: 0, removable: true, addable: false, isDefault: true },
    ],
    includeFries: true,
  },
  {
    id: "podium-burger",
    name: "Podium",
    description: "Hambúrguer vegetariano com cogumelos grelhados e queijo",
    basePrice: 26,
    category: "burger",
    image: "/vegetarian-burger-with-mushrooms.jpg",
    ingredients: [
      {
        id: "veggie-patty",
        name: "Hambúrguer Vegetariano",
        price: 0,
        removable: false,
        addable: false,
        isDefault: true,
      },
      { id: "mushroom", name: "Cogumelos Grelhados", price: 0, removable: true, addable: false, isDefault: true },
      { id: "cheese", name: "Queijo", price: 0, removable: true, addable: true, isDefault: true },
      { id: "lettuce", name: "Alface", price: 0, removable: true, addable: false, isDefault: true },
      { id: "tomato", name: "Tomate", price: 0, removable: true, addable: false, isDefault: true },
    ],
    includeFries: true,
  },
  {
    id: "turbo-fries",
    name: "Batata Turbo",
    description: "Batatas fritas crocantes com tempero especial",
    basePrice: 12,
    category: "side",
    image: "/crispy-french-fries.png",
  },
  {
    id: "onion-rings",
    name: "Onion Rings",
    description: "Anéis de cebola empanados e fritos",
    basePrice: 14,
    category: "side",
    image: "/golden-onion-rings.jpg",
  },
  {
    id: "chicken-wings",
    name: "Asas de Frango",
    description: "Asas de frango crocantes com molho barbecue",
    basePrice: 22,
    category: "side",
    image: "/crispy-chicken-wings.jpg",
  },
  {
    id: "cola",
    name: "Refrigerante",
    description: "Lata 350ml",
    basePrice: 6,
    category: "drink",
    image: "/soda-can.png",
  },
  {
    id: "juice",
    name: "Suco Natural",
    description: "Laranja ou Limão - 400ml",
    basePrice: 10,
    category: "drink",
    image: "/orange-juice-glass.png",
  },
  {
    id: "milkshake",
    name: "Milkshake",
    description: "Chocolate, Morango ou Baunilha - 500ml",
    basePrice: 16,
    category: "drink",
    image: "/milkshake-glass.jpg",
  },
  {
    id: "combo-champion",
    name: "Combo Campeão",
    description: "Grand Prix + Batata Turbo + Refrigerante",
    basePrice: 58,
    category: "combo",
    image: "/burger-combo.png",
  },
  {
    id: "combo-rookie",
    name: "Combo Rookie",
    description: "Pole Position + Batata Turbo + Refrigerante",
    basePrice: 38,
    category: "combo",
    image: "/burger-fries-drink-combo.jpg",
  },
]
