import type { Product, Ingredient } from "./types"

export const baseIngredients: Ingredient[] = [
  { id: "meat", name: "Carne de Hambúrguer", price: 0, removable: false, addable: true, isDefault: true },
  { id: "cheese", name: "Queijo", price: 0, removable: true, addable: true, isDefault: true },
  { id: "lettuce", name: "Alface", price: 0, removable: true, addable: false, isDefault: true },
  { id: "tomato", name: "Tomate", price: 0, removable: true, addable: false, isDefault: true },
  { id: "onion", name: "Cebola", price: 0, removable: true, addable: false, isDefault: true },
  { id: "pickle", name: "Picles", price: 0, removable: true, addable: false, isDefault: true },
  { id: "sauce", name: "Molho Especial", price: 0, removable: true, addable: false, isDefault: true },
]

export const extraIngredients: Ingredient[] = [
  { id: "bacon", name: "Bacon", price: 5, removable: false, addable: true, isDefault: false },
  { id: "egg", name: "Ovo", price: 4, removable: false, addable: true, isDefault: false },
  { id: "extra-cheese", name: "Queijo Extra", price: 3, removable: false, addable: true, isDefault: false },
  { id: "extra-meat", name: "Carne Extra", price: 8, removable: false, addable: true, isDefault: false },
]

export const products: Product[] = [
  {
    id: "power-crunch",
    name: "RB POWER CRUNCH",
    description: "Com pão brioche, dois smashes de 80g, cheddar, bacon, molho doritos e picles, este hambúrguer traduz a potência agressiva da Red Bull: os dois smashes simbolizam a dupla competitiva da equipe, enquanto o cheddar e o bacon reforçam intensidade e o molho doritos traz o toque ousado que marca o estilo da RBR.",
    basePrice: 28,
    category: "burger",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/12338564/picture/large/251124181554",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "scuderia-rossa-parma",
    name: "SCUDERIA ROSSA PARMA",
    description: "Pão brioche, frango empanado crocante, molho de tomate artesanal, muçarela e orégano criam uma combinação totalmente italiana, perfeita para representar a Ferrari. O molho vermelho remete ao clássico “Rosso Corsa”, enquanto a simplicidade saborosa simboliza tradição e elegância.",
    basePrice: 28,
    category: "burger",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/12338566/picture/large/251124181557",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "silver-arrow-triplo-bacon",
    name: "SILVER ARROW TRIPLO",
    description: "Com três carnes smash de 80g, cheddar, bacon e cebola grelhada, este hambúrguer robusto homenageia o domínio histórico da Mercedes: os três smashes representam seus anos de supremacia, e os sabores intensos remetem à força e consistência dos “Silver Arrows”.",
    basePrice: 38,
    category: "burger",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7839288/picture/large/250110201605",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "papaya-speed",
    name: "PAPAYA SPEED",
    description: "Um blend de 180g com queijo prato, american sauce, alface americana e tomate, simples porém veloz, faz referência ao estilo direto e moderno da McLaren. O sabor leve e equilibrado combina com a identidade papaya e com a evolução aerodinâmica do time.",
    basePrice: 28,
    category: "burger",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7839258/picture/large/250110201957",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "green-prime",
    name: "ASTON GREEN PRIME",
    description: "Tiras de costela bovina, queijo prato, cebola crispy e barbecue criam um hambúrguer encorpado que reflete o visual sofisticado da Aston Martin. A costela representa força e luxo, enquanto o barbecue adiciona personalidade refinada — exatamente como o DNA da equipe britânica.",
    basePrice: 28,
    category: "burger",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7839340/picture/large/250110202100",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "blue-original",
    name: "WILLIAMS BLUE ORIGINAL",
    description: "Com blend de 180g, muçarela, ovo, bacon e banana da terra frita, esta combinação clássica representa a história profunda da Williams. O ovo e bacon remetem ao tradicionalismo da equipe, enquanto a banana traz um toque inesperado, assim como seus momentos de brilho ao longo dos anos.",
    basePrice: 28,
    category: "burger",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7839368/picture/large/250110202129",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "french-chimi",
    name: "ALPINE FRENCH CHIMI",
    description: "Blend de 180g, muçarela, cebola roxa, maionese chimichurri e rúcula criam um sabor europeu marcante, representando o estilo francês da Alpine. A rúcula e o chimichurri trazem frescor e personalidade, alinhados com a atitude técnica e esportiva da equipe.",
    basePrice: 28,
    category: "burger",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7839380/picture/large/250110202203",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "american-grill",
    name: "HAAS AMERICAN GRILL",
    description: "Com duas carnes de 80g, queijo ementhal, alface americana, cebola, picles e molho especial, este hambúrguer grande e direto ao ponto captura a identidade americana da Haas. Forte, clássico e sem enrolação, como a proposta da equipe.",
    basePrice: 28,
    category: "burger",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7839499/picture/large/250519205823",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "tech-brie-max",
    name: "SAUBER TECH BRIE MAX",
    description: "Blend de 180g, queijo prato, brie empanado, geleia de pimenta e cebola roxa formam uma combinação moderna, perfeita para representar a identidade tecnológica da Sauber/Kick. O brie empanado simboliza inovação e a geleia de pimenta traz ousadia — marca registrada de um time em evolução.",
    basePrice: 28,
    category: "burger",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7839422/picture/large/250110202232",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "aero-authentico",
    name: "VCARB AERO AUTHENTICO",
    description: "Com blend de 180g, cheddar normal e cheddar empanado, bacon e geleia de pimenta, este hambúrguer expressa a jovialidade e agressividade da Visa RB. O cheddar empanado adiciona impacto visual e sabor, enquanto a geleia de pimenta evoca o estilo criativo e dinâmico da equipe.",
    basePrice: 28,
    category: "burger",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7839413/picture/large/250110202215",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "pit-stop-fries",
    name: "Pit Stop Fries",
    description: "Clássicas e diretas, como a freada no S do Senna. Ganham um toque de páprica para representar o calor da torcida brasileira.",
    basePrice: 12,
    category: "side",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7838323/picture/large/250110200949",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "monte-carlo-brie-bites",
    name: "Monte Carlo Brie Bites",
    description: "Elegância total: crocância fina e sabor sofisticado, dignos das ruas mais luxuosas do principado. Servido com geleia dourada especial.",
    basePrice: 12,
    category: "side",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7838395/picture/large/250110201313",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "curva-parabolica-croquete",
    name: "Curva Parabólica Croquete",
    description: "Potente e cheio de personalidade, como a curva mais famosa de Monza. A costela ganha uma pitada de ervas italianas.",
    basePrice: 12,
    category: "side",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7838350/picture/large/250110201249",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "suzuka-tempura-rings",
    name: "Suzuka Tempura Rings",
    description: "Anéis crocantes com leve toque oriental, lembrando a precisão das curvas do circuito japonês.",
    basePrice: 12,
    category: "side",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7838424/picture/large/240930224926",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "texas-safety-car-fries",
    name: "Texas Safety Car Fries",
    description: "Cheddar generoso e bacon crocante, estilo do sul dos EUA — potência pura, igual ao ronco dos motores em Austin.",
    basePrice: 12,
    category: "side",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7838335/picture/large/250110201228",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "silverstone-cheese-balls",
    name: "Silverstone Cheese Balls",
    description: "Tradicionais como a casa da F1: as bolinhas recebem toque de mostarda inglesa cremosa para um sabor autêntico.",
    basePrice: 12,
    category: "side",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/11549123/picture/large/250128010047",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "night-race-coxinha",
    name: "Night Race Coxinha",
    description: "Inspirada na corrida noturna: crosta mais dourada e geleia de pimenta ligeiramente mais intensa — combina com o calor do deserto.",
    basePrice: 12,
    category: "side",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7838359/picture/large/250110201305",
    ingredients: [...baseIngredients],
    includeFries: true,
  },
  {
    id: "cola",
    name: "Refrigerante",
    description: "Lata 350ml",
    basePrice: 6,
    category: "drink",
    image: "/soda-can.png",
  },
  {
    id: "juice",
    name: "Suco Natural",
    description: "Laranja ou Limão - 400ml",
    basePrice: 10,
    category: "drink",
    image: "/orange-juice-glass.png",
  },
  {
    id: "milk-shake",
    name: "Milk Shake Box Box",
    description: "Milk shake de Ovomaltine com cobertura de chantilly – 500 ml. Uma parada obrigatória nos boxes: cremoso, rápido e cheio de energia, como um pit stop perfeito. O crunch do Ovomaltine representa a vibração da pista, enquanto o chantilly simboliza a espuma levantada pelos pneus na largada.",
    basePrice: 30,
    category: "dessert",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/10988952/picture/large/250203205624",
  },
  {
    id: "ice-cream",
    name: "Räikkönen Ice Cream",
    description: "Duas bolas de sorvete tão frias que fariam o próprio Kimi pedir um cobertor. Uma homenagem ao “Iceman” — direto ao ponto, simples e gelado, como suas entrevistas lendárias.",
    basePrice: 12,
    category: "dessert",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7855028/picture/large/220610200317",
  },
  {
    id: "brownie",
    name: "Brownie Iceman Mode",
    description: "Brownie quentinho por fora… mas acompanhado de um sorvete que mantém a temperatura emocional do Kimi: -273°C. A combinação perfeita entre o calor de uma vitória e a frieza de quem só quer “deixar eu fazer meu trabalho”.",
    basePrice: 31,
    category: "dessert",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7855034/picture/large/221126144512",
  },
  {
    id: "petit-gateau",
    name: "Petit Gateau Freeze & Go",
    description: "Um clássico: bolo quente e cremoso, contrastando com o sorvete tão gelado que poderia ser confundido com o humor do Räikkönen no rádio. Uma sobremesa que equilibra “calma e gelo”, exatamente como o Iceman pilotando na chuva.",
    basePrice: 33,
    category: "dessert",
    image: "https://www.goomer.app/webmenu/victoria-burger/product/7855048/picture/large/240709170234",
  }
]
